# Assignment: Data Wrangling

**Q1.** Open the "tidy_data.pdf" document in the repo, which is a paper called Tidy Data by Hadley Wickham.

  1. Read the abstract. What is this paper about?
  2. Read the introduction. What is the "tidy data standard" intended to accomplish?
  3. Read the intro to section 2. What does this sentence mean: "Like families, tidy datasets are all alike but every messy dataset is messy in its own way." What does this sentence mean: "For a given dataset, itâ€™s usually easy to figure out what are observations and what are variables, but it is surprisingly difficult to precisely define variables and observations in general."
  4. Read Section 2.2. How does Wickham define values, variables, and observations?
  5. How is "Tidy Data" defined in section 2.3?
  6. Read the intro to Section 3 and Section 3.1. What are the 5 most common problems with messy datasets? Why are the data in Table 4 messy? What is "melting" a dataset?
  7. Why, specifically, is table 11 messy but table 12 tidy and "molten"?
  8. Read Section 6. What is the "chicken-and-egg" problem with focusing on tidy data? What does Wickham hope happens in the future with further work on the subject of data wrangling?

1. From the abstract, this paper deals with how datasets should be oreinted in a 'tidy' way, with columns and rows relating to varaibles and observations respectively. This standardized framework gives a template for how to arrange messy data, and streamlines the eventual analysis aspect.
2. The tiny data standard is intended to a form of data cleaning that is approachable to statisticians, as well as making subsequent analysis easier. The end goal is to make the development of said analysis tools easier as well since datasets would be organized according to shared principles.
3. The sentence references how clean datasets will be similar/identical, just like happy families. This is the opposite of messy data, that often has its own unique issues that need to be solved. The second sentences referenes how easy it often is to identify what rows/columns are in regards to being an observation or variable; however, it is more difficult to precisely explain what that observation is and how it should be translated.
4. Wickham defines values as being either numbers of strings that are then organized. Variables represent one way of organizing, with a variable being all the values that can describe an attribute (degrees for temp as an example). An observation is the other way, which relates to all the values that full under a unit of whatever is being observed (often a person or year/day).
5. Tidy data is described as a standardized way of. taking the strucutre of the dataset and giving it a meaning. Often to simplify further analysis.
6. Column headers as values, not variable names, more than one variable in a column, variables are in columns and rows, multiple observations in the same table, a singular observation is stored in multiple tables. In the case of table 4, the variables are not all columns, but instead income is a row. Melting is taking issues like this and placing all variables into columns.
7. Table 11 is messy given its poor represenation of the days in. amonth, instead of being tidy it ends up with tons of empty values. Table 12 ends up as tidy since it took the undesirable year, month, and day into a cohesive 'date' column.
8. In order to get real benefits out of the tidy data frameowrk, you need the right tools/processes. Without these tools, putting data in the tidy system isn't super useful and thus it likely won't be done. He hopes that people cna use tidy data as a jumping off point to inspire new, innovative forms of data wrangling. He also hopes to study more about the cognitive side to further improve his system.

**Q2.** This question provides some practice cleaning variables which have common problems.
1. Numeric variable: For `./data/airbnb_hw.csv`, clean the `Price` variable as well as you can, and explain the choices you make. How many missing values do you end up with? (Hint: What happens to the formatting when a price goes over 999 dollars, say from 675 to 1,112?)
2. Categorical variable: For the `./data/sharks.csv` data covered in the lecture, clean the "Type" variable as well as you can, and explain the choices you make.
3. Dummy variable: For the pretrial data covered in the lecture, clean the `WhetherDefendantWasReleasedPretrial` variable as well as you can, and, in particular, replace missing values with `np.nan`.
4. Missing values, not at random: For the pretrial data covered in the lecture, clean the `ImposedSentenceAllChargeInContactEvent` variable as well as you can, and explain the choices you make. (Hint: Look at the `SentenceTypeAllChargesAtConvictionInContactEvent` variable.)

In [2]:
import pandas as pd
! git clone https://github.com/DS3001/wrangling

Cloning into 'wrangling'...
remote: Enumerating objects: 83, done.
remote: Counting objects: 100% (40/40), done.
remote: Compressing objects: 100% (29/29), done.
remote: Total 83 (delta 31), reused 11 (delta 11), pack-reused 43
Receiving objects: 100% (83/83), 10.85 MiB | 17.63 MiB/s, done.
Resolving deltas: 100% (36/36), done.

In [9]:
#1
df = pd.read_csv('/content/wrangling/assignment/data/airbnb_hw.csv')
df.head(5)

,Host Id,Host Since,Name,Neighbourhood,Property Type,Review Scores Rating (bin),Room Type,Zipcode,Beds,Number of Records,Number Of Reviews,Price,Review Scores Rating
0,5162530,NaN,1 Bedroom in Prime Williamsburg,Brooklyn,Apartment,NaN,Entire home/apt,11249.0,1.0,1,0,145,NaN
1,33134899,NaN,"Sunny, Private room in Bushwick",Brooklyn,Apartment,NaN,Private room,11206.0,1.0,1,1,37,NaN
2,39608626,NaN,Sunny Room in Harlem,Manhattan,Apartment,NaN,Private room,10032.0,1.0,1,1,28,NaN
3,500,6/26/2008,Gorgeous 1 BR with Private Balcony,Manhattan,Apartment,NaN,Entire home/apt,10024.0,3.0,1,0,199,NaN
4,500,6/26/2008,Trendy Times Square Loft,Manhattan,Apartment,95.0,Private room,10036.0,3.0,1,39,549,96.0

In [19]:
#1.1
price = df['Price']
price.unique() #find commas in values in the thousands so its a string
price = price.str.replace(',','') #remove commas
price = pd.to_numeric(price) #convert from string to numeric
print(price.unique())
print('missing: ', sum(price.isnull())) #display number of missing

[  145    37    28   199   549   149   250    90   270   290   170    59
    49    68   285    75   100   150   700   125   175    40    89    95
    99   499   120    79   110   180   143   230   350   135    85    60
    70    55    44   200   165   115    74    84   129    50   185    80
   190   140    45    65   225   600   109  1990    73   240    72   105
   155   160    42   132   117   295   280   159   107    69   239   220
   399   130   375   585   275   139   260    35   133   300   289   179
    98   195    29    27    39   249   192   142   169  1000   131   138
   113   122   329   101   475   238   272   308   126   235   315   248
   128    56   207   450   215   210   385   445   136   247   118    77
    76    92   198   205   299   222   245   104   153   349   114   320
   292   226   420   500   325   307    78   265   108   123   189    32
    58    86   219   800   335    63   229   425    67    87  1200   158
   650   234   310   695   400   166   119    62   168   340   479    43
   395   144    52    47   529   187   209   233    82   269   163   172
   305   156   550   435   137   124    48   279   330  5000   134   378
    97   277    64   193   147   186   264    30  3000   112    94   379
    57   415   236   410   214    88    66    71   171   157   545  1500
    83    96  1800    81   188   380   255   505    54    33   174    93
   740   640  1300   440   599   357  1239   495   127  5999   178   348
   152   242   183   253   750   259   365   273   197   397   103   389
   355   559    38   203   999   141   162   333   698    46   360   895
    10    41   206   281   449   388   212   102   201  2750  4750   432
   675   167   390   298   339   194   302   211   595   191    53   361
   480  8000  4500   459   997   345   216   218   111   735   276    91
   490   850   398    36   775   267   625   336  2500   176   725  3750
   469   106   460   287   575   227   263    25   228   208   177   880
   148   116   685   470   217   164    61   645   699   405   252   319
   268   419   343   525   311   840   154   294   950   409   184   257
   204   241  2000   412   121   288   196   900   647   524  1750   309
   510  1495  1700   799   383   372   492   327  1999   656   224   173
   875  1170   795   690   146   465  1100   151   274   429   825   282
   256  1111   620   271   161    51   855   579  1174   430    20   899
   649   485   181   455  4000   243   342   590   560   374   437   232
   359   985    31   244   254   723   237   428   370    34  1400   580
  2520   221   749  1600  2695   306   202   680   570   520   223  2295
   213  1065   346    24   286   296   266    26   995  1368   393   182
   635   258   780   589   347  1250  1350   446  3200  1050  1650  1550
   975   323  6500  2499  1850  2250   715   461   540   356   439   384
   569  1900    22   785   626   830   318   444   321   401  1499   888
   369   770   386   366   344   630   313   597   262   509 10000   278
   312   789  1195   422    21   765  3500   945   326  3100  2486  3390
  1356  2599   472   454   328   396   291]
missing:  0

In [36]:
#2
df = pd.read_csv('/content/wrangling/assignment/data/sharks.csv', low_memory = False)
df.head(10)

<ipython-input-36-56cec83603af>:2: DtypeWarning: Columns (10,17,18,19,20,21,24) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/content/wrangling/assignment/data/sharks.csv')

,index,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,...,Unnamed: 246,Unnamed: 247,Unnamed: 248,Unnamed: 249,Unnamed: 250,Unnamed: 251,Unnamed: 252,Unnamed: 253,Unnamed: 254,Unnamed: 255
0,0,2020.02.05,05-Feb-2020,2020.0,Unprovoked,USA,Maui,NaN,Stand-Up Paddle boarding,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2020.01.30.R,Reported 30-Jan-2020,2020.0,Provoked,BAHAMAS,Exumas,NaN,Floating,Ana Bruna Avila,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,2020.01.17,17-Jan-2020,2020.0,Unprovoked,AUSTRALIA,New South Wales,Windang Beach,Surfing,Will Schroeter,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,2020.01.16,16-Jan-2020,2020.0,Unprovoked,NEW ZEALAND,Southland,Oreti Beach,Surfing,Jordan King,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,2020.01.13,13-Jan-2020,2020.0,Unprovoked,USA,North Carolina,"Rodanthe, Dare County",Surfing,Samuel Horne,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,5,2020.01.12,12-Jan-2020,2020.0,Unprovoked,THAILAND,Phang Nga Province,Nang Thong Beach,Swimming,Hans-Peter Malten,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,6,2020.01.07,07-Jan-2020,2020.0,Unprovoked,AUSTRALIA,Queensland,North West Island,Swimming,Miah Holmes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,7,2020.01.05,05-Jan-2020,2020.0,Unprovoked,AUSTRALIA,Western Australia,Cull Island / Esperance,Scuba diving,Gary Johnson,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,8,2020.01.03,03-Jan-2020,2020.0,Unprovoked,NEW CALEDONIA,NaN,Calana,NaN,Peter ___,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,9,2020.01.02,02-Jan-2020,2020.0,Questionable,AUSTRALIA,Western Australia,Esperance,Swimming after being swept off rocks,Eric Birighitti,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
#2.1
import numpy as np
df['Type'].unique()
df['Type'].value_counts()

NameError: name 'df' is not defined

In [38]:
#2.2
type2 = df['Type']
type2 = type2.replace(['Sea Disaster', 'Watercraft', 'Boat', 'Boating', 'Boatomg'], 'Vehicular') #Simplify categories related to vehicles
type2 = type2.replace(['Invalid', 'Questionable', 'Unconfirmed', 'Unverified', 'Under investigation'], 'Missing Data') #combine questionable categories

df['Type'] = type2
df['Type'].value_counts()

Unprovoked      4716
Provoked         593
Vehicular        583
Missing Data     565
Name: Type, dtype: int64

In [6]:
#3
url = 'http://www.vcsc.virginia.gov/pretrialdataproject/October%202017%20Cohort_Virginia%20Pretrial%20Data%20Project_Deidentified%20FINAL%20Update_10272021.csv'
df = pd.read_csv(url,low_memory=False) # Pulling data from website
df.head(5)

,InternalStudyID,REQ_REC#,Defendant_Sex,Defendant_Race,Defendant_BirthYear,Defendant_Age,Defendant_AgeGroup,Defendant_AgeatCurrentArrest,Defendant_AttorneyTypeAtCaseClosure,Defendant_IndigencyStatus,...,NewFelonySexualAssaultArrest_OffDate,NewFelonySexualAssaultArrest_ArrestDate,NewFelonySexualAssaultArrest_DaysBetweenContactEventandOffDate,NewFelonySexualAssaultArrest_DaysBetweenOffDateandArrestDate,NewFelonySexualAssaultArrest_DaysBetweenReleaseDateandOffDate,NewFelonySexualAssaultArrest_Disposition,Intertnalindicator_ReasonforExcludingFromFollowUpAnalysis,CriminalHistoryRecordsReturnedorCMSRecordsFoundforIndividual,DispRecordFoundforChargesinOct2017Contact_Atleast1dispfound,CrimeCommission2021ReportClassificationofDefendants
0,ADI00001,1,M,W,1986,31,3,31,99,99,...,,,,999,999,,4,1,0,Defendant could not be classified or tracked d...
1,ADI00007,3,M,B,1956,60,6,60,9,9,...,,,,999,999,,5,1,1,Defendant Detained Entire Pre-Trial Period_Und...
2,ADI00008,4,M,W,1990,27,3,27,9,9,...,,,,999,999,,5,1,1,Defendant Detained Entire Pre-Trial Period_Und...
3,CDI00036,6,M,B,1989,27,3,27,0,0,...,,,,999,999,,5,1,1,Defendant Detained Entire Pre-Trial Period_Und...
4,CDI00038,7,F,W,1988,28,3,28,0,0,...,,,,999,999,,0,1,1,New criminal offense punishable by incarcerati...

In [7]:
#3.1
released = df['WhetherDefendantWasReleasedPretrial']
released.unique()
released = released.replace(9, np.nan) #remove incomplete data points
print(released.value_counts())
df['WhetherDefendantWasReleasedPretrial'] = released #sent edits back to data frame

1.0    19154
0.0     3801
Name: WhetherDefendantWasReleasedPretrial, dtype: int64

In [20]:
#4
import pandas as pd
import numpy as np
sentence = df['ImposedSentenceAllChargeInContactEvent']
sentence = pd.to_numeric(sentence, errors='coerce') #sentence becomes numeric type
print(sum(sentence.isnull()))
type = df['SentenceTypeAllChargesAtConvictionInContactEvent']
print(pd.crosstab((sentence.isnull()), type), '\n') #Cat 4 is where charges were dismissed

sentence = sentence.mask(type == 4, 0) #Replace length with 0 when type is 4
sentence = sentence.mask(type == 9, np.nan) # Replace length with np.nan when type is 9

print(sum(sentence.isnull())) # see how many are missing -- better
print(pd.crosstab((sentence.isnull()), type)) #confirm its fixed

df['ImposedSentenceAllChargeInContactEvent'] = sentence #reassign back to dataframr

274
SentenceTypeAllChargesAtConvictionInContactEvent     0     1    2     4    9
ImposedSentenceAllChargeInContactEvent
False                                             8720  4299  914  8779    0
True                                                 0     0    0     0  274

274
SentenceTypeAllChargesAtConvictionInContactEvent     0     1    2     4    9
ImposedSentenceAllChargeInContactEvent
False                                             8720  4299  914  8779    0
True                                                 0     0    0     0  274

# New Section

**Q3.** Many important datasets contain a race variable, typically limited to a handful of values often including Black, White, Asian, Latino, and Indigenous. This question looks at data gathering efforts on this variable by the U.S. Federal government.

1. How did the most recent US Census gather data on race?
2. Why do we gather these data? What role do these kinds of data play in politics and society? Why does data quality matter?
3. Please provide a constructive criticism of how the Census was conducted: What was done well? What do you think was missing? How should future large scale surveys be adjusted to best reflect the diversity of the population? Could some of the Census' good practices be adopted more widely to gather richer and more useful data?
4. How did the Census gather data on sex and gender? Please provide a similar constructive criticism of their practices.
5. When it comes to cleaning data, what concerns do you have about protected characteristics like sex, gender, sexual identity, or race? What challenges can you imagine arising when there are missing values? What good or bad practices might people adopt, and why?
6. Suppose someone invented an algorithm to impute values for protected characteristics like race, gender, sex, or sexuality. What kinds of concerns would you have?

1. The US Census has people self-identify their race and allows them to pick multiple options as well as select their ethnicity. These options come from preselected categories that cover multiple sub categories.
2. Census data is allegedly collected to inform the government for things like vote allocation and eventually funding. In politics, house seats are assigned according to population, but often politics uses race/religious information in gerrymandering efforts. For society, this info is supposed to go towards informing government intiatives aimed at certain demographics. Data quality is extremely important when things like congressional seats are being determined, this extends to ensuring funds are sent to the right areas.
3. With the census often being sent out in the mail, it risks missing anyone who might find themselves displaced from a permanent address. Practically, I do commend the Census Bureau for how well they handle having to get data on hundreds of millions of individuals. I think the political coverage of President Trump wanting to ignore undocumented immigrants created tension around counting them.
4. For a category like race, there is a legitimate case to be made that the overarching categories are quite limiting. To better capture diversity, the most basic change is just to allow the collection of more data points for the various subcategories of each race. However, the current form is basically a version of data wrangling that would later be done by a researcher. I think gender is likely a massive shortcoming of the current census process, particuarly given that many identify outside of male or female. I think it would be improved by having other options. I think the option to select more than one race in the census is still a very good thing that many other surveys do not do.
5. I am majorly concerned over how future data scientists might use the excuse of data cleaning to not count, or simply, those that do not fit into neat gender or racial categories. If there is a missing value from someone who might not be comfortable, I can easily see someone simply wiping that observation from the dataset, removing their say. Another option is the idea that policymakers might abuse that info in order to attack certain groups. I think a first step is just making sure that data scientists receive the right education on handling these sensitive identites, and appreciate the nuance before they wipe an observation off the dataset.
6. I am hesitant to trust any for of algorithm that deals with sensistive categories. This is becuase these bits of code often make unintentional mistakes that directly harm these groups. Even if that didn't occur, a value might still fail to encapsulate the nuances of those identities.